apiVersion: v1
kind: Service
metadata:
  name: hacker-news-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: hacker_news
  ports:
    - name: hacker-news-srv
      port: 3000
      targetPort: 3000
      protocol: TCP
